### ISSUE TITLE
charset issue when translate english into chinese

### ISSUE THREAD

**Issue by wywzxxz** [MicrosoftTranslator/DocumentTranslator#1]
when  translate english into Chinese, sometimes some sentence or even the entire paper can't be displayed appropriate.
![default](https://cloud.githubusercontent.com/assets/5335612/8957436/06728dec-3631-11e5-8443-f8fadb223ef4.png)

But it is actually not been damaged , I copyed the word I marked above and pasted it to the notepad and It become "摘要"  which is the right content.
So I think may be it is about the charset, such as marked as UTF-8 but turn out to be G2312 or what, But I can't verify this assumption since I don't know how to parse doc...

---------------------------------------------------
Above assumption is WRONG.
It turned out to be caused by lacking Font in word.... guys could you tell me how you pick up fonts for Chinese? thx~

**Comment by chriswendt1** [comment]
Hi wywzxxz,

Indeed Document Translator makes no attempt to change the font, it retains the originally assigned font. Usually the empty square indicates a missing glyph.
You can use "Arial Unicode" as a font that works across the range. 

Hope this helps,
Chris Wendt
Microsoft Translator
