### ISSUE TITLE
XamarinStudio support

### ISSUE THREAD

**Issue by loretoparisi** [MicrosoftTranslator/DocumentTranslator#10]
Would it work in XamarinStudio?

**Comment by chriswendt1** [comment]
I don't know. What would be needed to run in Xamarin Studio?
It would be easy to add translation of various resource formats, if you mean that.

**Comment by chriswendt1** [comment]
If you want to translate your resource files in Visual Studio, see whether MAT woks for you:
https://www.microsoft.com/en-us/translator/mat.aspx.

**Comment by loretoparisi** [comment]
@chriswendt1 since we are working on `macOS` and `Linux` only at this time, and I assume that I could run the binaries in `mono`, but to build it could be not that easy.

**Comment by loretoparisi** [comment]
I suppose that this will going to work in `VisualStudio for Mac` announcing tomorrow 👍

**Comment by chriswendt1** [comment]
Would need to be ported to .Net core, including the user libraries like HTML Agility Kit and OpenXML libs. You may attempt that, but probably easier to start with a full rewrite.
