### ISSUE TITLE
Does the DocumentTranslator app support Azure china translation services?

### ISSUE THREAD

**Issue by imzhu** [MicrosoftTranslator/DocumentTranslator#105]
DocumentTranslator 这个APP是否支持 中国区的Azure翻译服务

ERROR Unauthorized { "error": { "code": 401000, "message": "The request is not authorized because credentials are missing or invalid." } }

**Comment by chriswendt1** [comment]
It requires code changes.  I take this as a feature request. It appears you have credentials for Azure China, which is good. The Azure China key doe snot work in Azure Global, and the client won't know that the key is valid in Azure China, until one of us implements the option to select Azure China.

**Comment by chriswendt1** [comment]
I intended to fix this in version 2.7.0. Please give it a try and let me know.
