### ISSUE TITLE
DocumentTranslater removed by Windows Defender

### ISSUE THREAD

**Issue by gnarr** [MicrosoftTranslator/DocumentTranslator#11]
![translatordefender](https://cloud.githubusercontent.com/assets/5297870/18413508/570d4350-7799-11e6-8107-6092fa30039c.PNG)

**Comment by TehBotolSosro** [comment]
i also have the same issue

**Comment by chriswendt1** [comment]
Probably because it is not signed. I'll get it signed.

**Comment by chriswendt1** [comment]
There is now a signed version 2.1.0. Please let me know how that worked.
