### ISSUE TITLE
Timeout for the first call to a Custom Translator system

### ISSUE THREAD

**Issue by chriswendt1** [MicrosoftTranslator/DocumentTranslator#110]
Document Translator times out when using a custom translation system after a longer period of non-use. Need to redo the retry logic.

**Comment by jbenoit862** [comment]
We are using Document Translator version 2.1.1 and Custom Translator. 
When we submit a French document to be translated into English, it does not get translated on the first trial.  We get an error message in Document Translator and do receive a file with the .en extension but the document is still in French or sometimes the document gets partly translated.  Usually on the second or on the third trial the entire document is translated.  It appears that Document Translator needs to be «warmed up». The behavior just described happens with Word and PowerPoint documents. This is very frustrating.
Is this the reason why ? Thanks.

**Comment by chriswendt1** [comment]
Fixed in version 2.6.
