### ISSUE TITLE
Ver. 2.3.0 does not accept the Keys

### ISSUE THREAD

**Issue by LaoMa1961** [MicrosoftTranslator/DocumentTranslator#113]
Hello,

I'd like to outline that the ver. 2.3.0 doesn't accept the key copied from Azure Portal Translator Cognitive Service....
![image](https://user-images.githubusercontent.com/61132391/74694314-a21af080-522a-11ea-8333-0d3bc1fd2eee.png)

Thanks

PS: I am trying to find a version which works with W10, at the moment no one seems good.
I tried the last one and the 2.3.0 .... 😒

**Comment by SCOMnewbie** [comment]
Hi @LaoMa1961 . Could you check if the issue that I've closed yesterday isn't the same problem? Are you sure that it's a translator text key and not a general cognitive service key?

**Comment by LaoMa1961** [comment]
i will.  which version do I have to install,  please? about keys,  I am sure,  it is notbthev1st time I do.  it doesn't save both key1 and key2. the issue is that everytime I have to save again...  not a big one but I am sure it is not the wanted behavior. Inviato dal mio telefono Huawei-------- Messaggio originale --------Da: SCOMnewbie <notifications@github.com>Data: mar 18 feb 2020, 21:56A: MicrosoftTranslator/DocumentTranslator <DocumentTranslator@noreply.github.com>Cc: LaoMa1961 <m.bonelli@libero.it>, Mention <mention@noreply.github.com>Oggetto: Re: [MicrosoftTranslator/DocumentTranslator] Ver. 2.3.0 does not accept the Keys (#113)Hi @LaoMa1961 . Could you check if the issue that I've closed yesterday isn't the same problem? Are you sure that it's a translator text key and not a general cognitive service key?

**Comment by chriswendt1** [comment]
Please try version 2.5.5. and use a Translator Text resource key..

**Comment by LaoMa1961** [comment]
Ok. I will try the 2.5.5 and then report you later…. 

Sent from Mail for Windows 10

**Comment by LaoMa1961** [comment]
I have installed the 2.5.5 and it crashes. 
1st time it crashed just after opening
2nd time it crashed after I saved the key
Then I made a Repair from the installation program
3rd time it crashed when I was browsing the file...

OS is W10 Pro 10.0.18363

I have to reinstall 2.1.1

Sorry.....
