### ISSUE TITLE
The cmdline tool returns an error on "zh-hans" and "zh-hant"

### ISSUE THREAD

**Issue by honghuiguo** [MicrosoftTranslator/DocumentTranslator#116]
I run the below translation request and get an error on simplified Chinese and traditional Chinese. The input document can be any txt file. Other languages are fine. And the GUI tool is fine. 
![image](https://user-images.githubusercontent.com/63156442/78454069-9ce2fb00-764a-11ea-9914-06094a9f8b54.png)

**Comment by chriswendt1** [comment]
Fixed in version 2.6.1.
