### ISSUE TITLE
Key is Invalid

### ISSUE THREAD

**Issue by TironAndric** [MicrosoftTranslator/DocumentTranslator#119]
Trying to use the latest 2.6 but I am unable to confirm the key, tried both 1 and 2 and I get Key is invalid. 

Note: I tried to find "Translator Text API keys" but all I could find is Cognitive Service API when I go to Congnitive Services\Keys and Endpoint

**Comment by chriswendt1** [comment]
Please use a key in the "Global" region. That's the only region that works in 2.6. I'll be fixing this by Monday.

**Comment by TironAndric** [comment]
Just to confirm that once the region is set to "Global" everything works fine.

**Comment by chriswendt1** [comment]
Version 2.7.0 works with keys from any region. Need to specify the region of the resource your key is for. "Global" still works.
