### ISSUE TITLE
Document Translator does not translate footnotes in Word 2016

### ISSUE THREAD

**Issue by mbalcerzyk** [MicrosoftTranslator/DocumentTranslator#12]
Document Translator does not translate footnotes in Word 2016, at least in translation from English to Polish.

**Comment by chriswendt1** [comment]
OK, I'll try to debug that. Thanks for reporting. Relying on the OpenXML libraries to extract the relevant text, hopefully there is a function to extract the footnotes.

**Comment by mbalcerzyk** [comment]
Dear Chris.

 

Thank you. I recently did a machine  translation from English to Polish of 30 page document and I am not very happy with the quality. I am not a programmer myself and new to Github, but I can see what class of language errors the translation did. I thought I may contribute to improving the translation quality. Tell me if and how I may do it. I speak myself fluent Polish, English, Spanish and basic Russian. 

 

Kind regards. 

 

Marcin Balcerzyk

**Comment by chriswendt1** [comment]
Fixed in version 2.1.0. You also see much better quality now.
