### ISSUE TITLE
Lost the text "translation" tab from the top ribbon of Document Translator

### ISSUE THREAD

**Issue by rc175** [MicrosoftTranslator/DocumentTranslator#120]
Hi all,
I all of sudden lost  the functionality of text "**TRANSLATE**" tab from the top ribbon of Document Translator. I have tried reinstalling the application couple of times but the issue didn't resolve. I am currently using version 2.4.1 of document translator.It was working perfectly for last 4 months. Please see attached snapshots for more details.

Thanks
Raj
![TranslateTab](https://user-images.githubusercontent.com/62859681/83303321-d6f3f780-a1ca-11ea-92cb-c48ce78ce63b.jpg)
![TranslateTab2](https://user-images.githubusercontent.com/62859681/83303394-fb4fd400-a1ca-11ea-839d-0eec101f60a4.jpg)
![TranslateTab3](https://user-images.githubusercontent.com/62859681/83303415-030f7880-a1cb-11ea-9fd6-5dca82efea28.jpg)

**Comment by chriswendt1** [comment]
Please try version 2.6.3 or 2.7.0. The Translate tab is solidly there.
