### ISSUE TITLE
What is categoryID/clientSecret/clientID ?

### ISSUE THREAD

**Issue by felixhao28** [MicrosoftTranslator/DocumentTranslator#14]
When I try to use DocumentTranslatorCmd, it prompts `Invalid translation service credentials. Use "DocumentTranslatorCmd setcredentials", or use the Document Translator Settings option.`. And `DocumentTranslatorCmd setcredentials /?` tells me to enter categoryID, clientSecret and clientID. I looked everywhere in my Azure Portal and cannot find those keywords.

I did find Subscription ID and KEY 1 and KEY 2. Are they related?

**Comment by felixhao28** [comment]
Alright I got this after I found this document: http://docs.microsofttranslator.com/text-translate.html

clientSecret and clientID are both used to retrieve access tokens. However if you started from [this welcome page](https://www.microsoft.com/cognitive-services/), you will be prompted to create an Azure Cognitive Services APIs (preview) account and that eventually leads you to [Azure Portal](https://portal.azure.com), where you don't use clientSecret/clientID but _subscription key_ instead. [This article](http://docs.microsofttranslator.com/oauth-token.html) tells you how you get access token with subscription key (either KEY 1 or KEY 2).

In this sense, I feel this demo tool is kind of outdated. I will see if I can manage to make a PR to fix this.

**Comment by felixhao28** [comment]
And categoryID is related to a custom model used in https://hub.microsofttranslator.com. I figured that out.

**Comment by chriswendt1** [comment]
Sorry for being late. Document Translator is now ready to work with an Azure subscription, taking the Key form your resource as authentication. The newest binaries and the branch AzureAuth2 contain the version working with an Azure subscription.
