### ISSUE TITLE
F-DROID Possible?

### ISSUE THREAD

**Issue by dm17** [MicrosoftTranslator/DocumentTranslator#140]
Is it possible to use this without the Google Play / Google Services dependency? I'm especially interested in getting at added to F-DROID.
Thanks!

**Comment by chriswendt1** [comment]
There is no such dependency. No Google services are used by this app. It is a Windows application.

**Comment by dm17** [comment]
Apologies, I thought it was in the Google Play store:
https://play.google.com/store/apps/details?id=com.microsoft.translator&hl=en&gl=US

**Comment by chriswendt1** [comment]
This Github project uses a commercial subscription to the Translator service that is part of Microsoft Azure. It runs on Windows, and is different from the the consumer app in the Google Play and Apple store.

**Comment by dm17** [comment]
> This Github project uses a commercial subscription to the Translator service that is part of Microsoft Azure. It runs on Windows, and is different from the the consumer app in the Google Play and Apple store.

Thanks! My goal is trying to get any of the available translators (Google, Microsoft, DeepL) into a browser extension such that web pages can be translated offline (like chromium does a great job with online).

**Comment by chriswendt1** [comment]
See this project: https://github.com/MicrosoftTranslator/Local-Feature-Android
You can call the local API exposed by the Translator app. It works offline, if the appropriate Microsoft Translator language pack is present.
