### ISSUE TITLE
Why did I fail to finish the code build?

### ISSUE THREAD

**Issue by daxin09pp** [MicrosoftTranslator/DocumentTranslator#141]
Please see the attachment. After I download the code, build will fail.This looks like a syntax error, right?

**Comment by daxin09pp** [comment]
![16077516221068](https://user-images.githubusercontent.com/12574090/101976433-263dd900-3c80-11eb-9988-6d1855dc1de7.png)

**Comment by chriswendt1** [comment]
I suspect you have Code Analysis warnings set to errors.

**Comment by chriswendt1** [comment]
If you didn't want to make modifications, you can download the binary.

**Comment by chriswendt1** [comment]
Found the problem: Please set the " Solution Platform" to " x86. Then the errors go away. The app is not suitable for other platforms. 
![image](https://user-images.githubusercontent.com/11096941/102729808-1f9a0c00-42e7-11eb-9e92-08dde3d9a4b9.png)
