### ISSUE TITLE
Issue in PDF translation

### ISSUE THREAD

**Issue by rohittilwani** [MicrosoftTranslator/DocumentTranslator#144]
Hi,
While trying to translate pdf, I am facing an error. I am able to translate .docx file perfectly. 

Initially there was another issue saying that "could not load file or assembly "Microsoft.Interop.Word, Version=15.0.0.0, Culture=neutral" or one of its dependencies." 
After I tried it on a Windows 10 machine having MS-office (version 18.2008.12711), I saw the following different error message. Any insight on What am I doing wrong here?

![Selection_044](https://user-images.githubusercontent.com/45655709/103641543-e795f880-4f77-11eb-82da-92ad943f3144.png)

**Comment by chriswendt1** [comment]
How did you solve the problem?
Making sure that you have a proper installation of Word and run Word once om this machines will resolve this.
Document Translator uses the installed version of Word to convert PDF to DOCX. 
If that fails, you can do this manually as well: Open the PDF in Word, save as DOCX, then translate the DOCX.

**Comment by rohittilwani** [comment]
Hi @chriswendt1 ,

I tried using a newer version of the MS-word and it resolved the error. 
Also, I was looking to contact the Microsoft Translator community to know about the terms and conditions under which this software can be used for commercial purposes, or is there an enterprise license for the same.

It would be great if you can help me with this information.

Thanks

**Comment by chriswendt1** [comment]
This Document Translator client is using the Translator service of Microsoft Azure. The Microsoft Azure terms and conditions apply for the service.
https://azure.microsoft.com/support/legal/
The client is open source, under the license provided in the license.md document.
