### ISSUE TITLE
 Set series colors in column charts

### ISSUE THREAD

**Issue by mwinner313** [MicrosoftTranslator/DocumentTranslator#147]
![image](https://user-images.githubusercontent.com/16043883/105032473-0b733700-5a6c-11eb-90f7-90105acd49f1.png)
 the left chart is created by c# and the right one is a sample created by word
i allready tested : 
![image](https://user-images.githubusercontent.com/16043883/105032600-39f11200-5a6c-11eb-8570-2d90ce5230bf.png)

please help me create a series like right bar in first image

**Comment by chriswendt1** [comment]
Hi @mwinner313, this is not a Document Translator question.
