### ISSUE TITLE
Error running under Windows 7

### ISSUE THREAD

**Issue by erkanozhan** [MicrosoftTranslator/DocumentTranslator#153]
Hello, looks like a great program. I wanted to try it excitedly. I'm still using Windows 7. I loaded the .msi file and ran it. I saw the attached error message. 
Good luck.

> Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	DocumentTranslator.exe
  Problem Signature 02:	0.1.0.0
  Problem Signature 03:	5f961f15
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.8.3928.0
  Problem Signature 06:	5d39000b
  Problem Signature 07:	5d23
  Problem Signature 08:	26
  Problem Signature 09:	FOPL4MYEJCHQ4QUDLY5M1JG1EE1KJYWU
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by chriswendt1** [comment]
Please try the command line utility in the DocumentTransla**tion** project. I have not tested it on Windows 7, but it has a higher chance of working there.
