### ISSUE TITLE
Adding support for more languages

### ISSUE THREAD

**Issue by abhi18av** [MicrosoftTranslator/DocumentTranslator#17]
Hii @chriswendt1 and Microsoft Team:)

Hey, I just curious about how to add support for languages like Kazakh or Mongolian ? Is there a way that I could be of help - I think the recent developments from Microsoft Research has been nothing short of fantastic :+1:

**Comment by chriswendt1** [comment]
https://hub.microsofttranslator.com allows you to build support for a new language from scratch, as long as that language uses space to break words.
