### ISSUE TITLE
Latest version do no work - Win 7

### ISSUE THREAD

**Issue by na1221** [MicrosoftTranslator/DocumentTranslator#22]
Hello

I get this error message right after opening. "Document translator have stopped working"

And there is only one button to close the program. The document translator never starts, just get that error message. And after install the program did never auto start.

OS Name	Microsoft Windows 7 Ultimate
Locale	United States

thanks

**Comment by chriswendt1** [comment]
Thanks for the report. Did the previous version work on Win7?
I changed the .Net Framework version in the newest version, I suspect that broke it

**Comment by na1221** [comment]
its my first time test the software.

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	documenttranslator.exe
  Problem Signature 02:	0.1.0.0
  Problem Signature 03:	55a44ff7
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.0.0
  Problem Signature 06:	4ba1da6f
  Problem Signature 07:	11cd
  Problem Signature 08:	89
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1053
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by chriswendt1** [comment]
Thanks. Did any version ever work on Windows 7?
I'll do whatever easy thing can be done, but beyond that you will want to consider upgrading to Windows 10.

**Comment by na1221** [comment]
I tried all versions, non was working. Why is that? Never experienced anything like that.

**Comment by chriswendt1** [comment]
Requires Windows 8 or later.
