### ISSUE TITLE
Issue with CTF functionality. Getting constant error while uploading TMX

### ISSUE THREAD

**Issue by HarshadPatel1988** [MicrosoftTranslator/DocumentTranslator#23]
Hi Team,

I am getting following error message while uploading TMX to CTF. Can you please look into it?
![untitled](https://cloud.githubusercontent.com/assets/24873488/22585829/c3d0fc2c-ea1f-11e6-87e7-12ab4e3db256.png)

**Comment by chriswendt1** [comment]
Saw it. Will have a look.

**Comment by HarshadPatel1988** [comment]
Hi Chris,

We are constantly getting this error and unable to access CTF framework with updated API. Is this fixed?

**Comment by chriswendt1** [comment]
@HarshadPatel1988: I do not find the problem you report.
I find other problems, like fewer sentences added than what I expected, and nothing written to the error CSV and error TMX. Can you show me the tmx you tried to upload, and the command line you used?

**Comment by HarshadPatel1988** [comment]
Hi Chris,

Attached is the snapshot of command line used. We have TMX files build using MemoQ CAT tool, which uses primarily UTF 8 encoding and have TM entries more than 70-80 thousands in most of cases.

![image](https://cloud.githubusercontent.com/assets/24873488/23597958/1f7aaeec-025d-11e7-8ffa-00529b60dc2b.png)

**Comment by HarshadPatel1988** [comment]
Hi Chris,

Have you got the chance to look into this?

**Comment by chriswendt1** [comment]
I have removed the CTF related functionality - CTF is deprecated in the Translator API.
