### ISSUE TITLE
Document Translator hangs if two instances are running

### ISSUE THREAD

**Issue by vitalii-dmytruk** [MicrosoftTranslator/DocumentTranslator#25]
In case two instances are running in parallel (via CLI) Document Translator hangs when trying to write to the same Log.txt file.

Scenario:
Start several translation using DocumentTranslatorCmd tool
The tool A tries to write log message to the Log.txt, but the file is locked by the tool B from another process
The tool A hangs.

Expected:
Simultaneous translations do not block each other.

**Comment by chriswendt1** [comment]
Thanks for fixing it!
