### ISSUE TITLE
API Key cannot be saved

### ISSUE THREAD

**Issue by assafi** [MicrosoftTranslator/DocumentTranslator#26]
The issue: when updating the key and clicking Save the message always says that the key is invalid.

While debugging the code I noticed the problem is in `AccountViewModel.cs`:

<pre><code>
        public AccountViewModel()
        {
            //Initialize in order to load the credentials.
            TranslationServices.Core.TranslationServiceFacade.Initialize();
            this.clientID = TranslationServices.Core.TranslationServiceFacade.ClientID; // <-- Secret is loaded only when screen is first initialized. Usually empty.
            this.categoryID = TranslationServices.Core.TranslationServiceFacade.CategoryID;
        }
        
        /// <summary>
        ///     Saves the account settings to the settings file for next use.
        /// </summary>
        private void SaveAccountClick()
        {
            //Set the Account values and save.
            TranslationServices.Core.TranslationServiceFacade.ClientID = this.clientID.Trim(); // <-- Overwriting the secret with the initial value (empty)
            TranslationServices.Core.TranslationServiceFacade.CategoryID = this.categoryID.Trim();
            TranslationServices.Core.TranslationServiceFacade.SaveCredentials();
            TranslationServices.Core.TranslationServiceFacade.Initialize();
            
            if (TranslationServices.Core.TranslationServiceFacade.IsTranslationServiceReady()) {  // <-- Key check fails for the empty key
            ...
</code></pre>

The fix seems to be fairly simple, and just removing the local variable. And always read from the password box.

<pre><code>
        public AccountViewModel()
        {
            //Initialize in order to load the credentials.
            TranslationServices.Core.TranslationServiceFacade.Initialize();
        }
        
        /// <summary>
        ///     Saves the account settings to the settings file for next use.
        /// </summary>
        private void SaveAccountClick()
        {
            //Set the Account values and save.
            TranslationServices.Core.TranslationServiceFacade.ClientID = TranslationServices.Core.TranslationServiceFacade.ClientID.Trim(); 
            TranslationServices.Core.TranslationServiceFacade.CategoryID = TranslationServices.Core.TranslationServiceFacade.CategoryID.Trim();
            TranslationServices.Core.TranslationServiceFacade.SaveCredentials();
            TranslationServices.Core.TranslationServiceFacade.Initialize();
            
            if (TranslationServices.Core.TranslationServiceFacade.IsTranslationServiceReady()) {  
            ...
</code></pre>

Since I don't really understand how this ever worked to begin with, I'm sure I'm probably missing something. Hence I'm not submitted a PR.

**Comment by chriswendt1** [comment]
Thanks @assafi. It didn't work before, so this is an OK change. Fixed in version 1.3.3, just uploaded now. 
The change you proposed and that I accepted is a violation of MVVM prescribed by PRISM. But I think we can let that go in favor of making it actually work...
