### ISSUE TITLE
Have you containerized the app?

### ISSUE THREAD

**Issue by holmbergius** [MicrosoftTranslator/DocumentTranslator#27]
Have you ever successfully containerized the application? We're interested in running DocumentTranslator from a Docker container, but we haven't been successful in getting MS Office 2013 on the container. Do you have any experience running DocumentTranslator from a container?

**Comment by chriswendt1** [comment]
Hi Jason,
I do not know how to run Office 2013 or later inside a Docker container. 
But maybe this helps: Document Translator doesn't need Office when translating Office 2013 or later OpenXML documents (the ones where the extension ends in 'x': docx, pptx, xlsx) or plain text or HTML.
It needs Office to translate Pre-Office 2013 formats (without the 'x' in the extension) and PDF.
If you convert the pre-Office 2013 and PDF docs to docx in some other process, you are golden.

**Comment by holmbergius** [comment]
Successfully implemented.
