### ISSUE TITLE
Document Translator do not translate text in PowerPoint speaker notes

### ISSUE THREAD

**Issue by kwafok** [MicrosoftTranslator/DocumentTranslator#28]
![image](https://cloud.githubusercontent.com/assets/7870790/24060416/1c8849a8-0b8e-11e7-96ae-7c9895920385.png)

I have used Document Translator V1.3.3U to translate a lecture PowerPoint from English to Chinese. It works really well but text in speaker notes do not translate...

**Comment by holmbergius** [comment]
This would be a great feature to have.

**Comment by chriswendt1** [comment]
Thanks for fixing it!
