### ISSUE TITLE
RPC errors

### ISSUE THREAD

**Issue by holmbergius** [MicrosoftTranslator/DocumentTranslator#31]
Can you please advise when and why RPC errors might occur?

I am regularly getting this error when testing the new Doc Translator with the new Azure API key and with the 1.0.2 stable release. It seems to happen occasionally on multiple, simultaneous calls (using different files for translation). But not always. Most requests succeed. But perhaps 1 in 5 or 1 in 10 fail with that error.

Thanks in advance,
Jason

The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
ERROR: An error has occurred.
**************************************
MESSAGE  : The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
SOURCE   : Microsoft.Office.Interop.Word
STACK    :    at Microsoft.Office.Interop.Word.ApplicationClass.Quit(Object& Sav
eChanges, Object& OriginalFormat, Object& RouteDocument)
   at TranslationAssistant.Business.DocumentTranslationManager.ConvertToDocx(Str
ing fullPath, String targetLanguage)
   at TranslationAssistant.Business.DocumentTranslationManager.GetAllDocumentsTo
Process(String documentPath, String targetLanguage)
   at TranslationAssistant.Business.DocumentTranslationManager.DoTranslation(Str
ing path, Boolean isDir, String sourceLanguage, String targetLanguage)
   at TranslationAssistant.AutomationToolkit.TranslationPlugins.TranslateDocumen
ts.Execute()
TARGET   : Void Quit(System.Object ByRef, System.Object ByRef, System.Object ByR
ef)
**************************************

**Comment by holmbergius** [comment]
I think it’s therefore a critical bug in Document Translator and how it connects to Word.

https://social.msdn.microsoft.com/Forums/en-US/2c8689e4-4f8c-42c1-b092-f8ae41b9779c/microsoftofficeinterop-word-and-the-rpc-server-is-unavailable-exception-from-hresult?forum=vbinterop

I can reproduce periodically when simultaneously translating two Word docs with two doc translators (independent command line windows).

The second comment from the bottom in that link describes what appears to be a simple fix. I am not a C# dev or would fix it myself otherwise. This would be an awesome fix to get.

Thank you!

**Comment by holmbergius** [comment]
We did a workaround and made changes\fixes to Doc Translator that have been committed back to the open source.

**Comment by chriswendt1** [comment]
Excellent. Thanks! I'll review your changes.
