### ISSUE TITLE
With 0 error segments nothing get added to CTF

### ISSUE THREAD

**Issue by HarshadPatel1988** [MicrosoftTranslator/DocumentTranslator#32]
Hi Chris,

While uploading TMX to CTF, after processing file, it says 0 entries written to CTF. Please refer attached snapshot for more details. Is this expected behaviour or it's any error?

![image](https://cloud.githubusercontent.com/assets/24873488/24319615/09649502-1147-11e7-97a7-516c9f71a42a.png)

**Comment by HarshadPatel1988** [comment]
Hi Team,

Do we have any update here?

**Comment by chriswendt1** [comment]
CTF is now deprecated. I have removed the related functionality in Document Translator. To be replaced with matching calls to the Hub API.
