### ISSUE TITLE
Build Solution not function

### ISSUE THREAD

**Issue by mauriliofilho** [MicrosoftTranslator/DocumentTranslator#38]
I have trying build solution for using my customizations, and i receive on arror in wixinstaller sdk light.exe and not opem aplication.

**Comment by chriswendt1** [comment]
Sorry no clue here. I used the regular Wix installer logic to build, nothing special. 
What customizations? If generally applicable, can you make a PR to integrate them? I'll rebuild the package.

**Comment by chriswendt1** [comment]
I updated the Wix package and it builds successfully, no more warnings. Please try again.
