### ISSUE TITLE
Settings page still shows client Id and secret (authentication problem)

### ISSUE THREAD

**Issue by vikas379** [MicrosoftTranslator/DocumentTranslator#39]
The settings page still shows client id and secret form even though the API has moved to azure and need only azure key.

**Comment by chriswendt1** [comment]
Really? Shouldn't be in the latest release binary and in the current master branch. if you are using the binary only, can you uninstall and reinstall? Version 1.3 and later should be Azure key only.

**Comment by vikas379** [comment]
Pre-release has the azure key in settings page. Thanks @chriswendt1
