### ISSUE TITLE
Neural MT: any changes needed here?

### ISSUE THREAD

**Issue by holmbergius** [MicrosoftTranslator/DocumentTranslator#40]
Just read this and want to use Neural MT with Doc Translator. Are any code changes needed?

https://blogs.msdn.microsoft.com/translation/2016/11/15/microsoft-translator-launching-neural-network-based-translations-for-all-its-speech-languages/

I was told this:

use category=generalnn in your API 

Is Document Translator capable of using that parameter in API calls yet?

Thank you!

**Comment by chriswendt1** [comment]
No code change needed. To use neural translation, enter "generalnn" in the "Category ID" field in the Settings tab.

**Comment by holmbergius** [comment]
Thank you! Can this be included from the command line as well?

**Comment by chriswendt1** [comment]
Yes. Using the setcredentials keyword with the cetegoryID parameter. Set the categoryID to "generalnn".

C:\Program Files (x86)\Microsoft Document Translator>DocumentTranslatorCmd.exe setcredentials /?
User activated plug-in help menu.
Usage details for [SetCredentials]

Plugin: SetCredentials

Sets the credentials for use with the Translator service.

==== Argument Descriptions ===================
All Arguments are of the form /<argName>:<argValue>


  APIkey              :API key to use for the calls to
                       the Translator service.

                       Required.

  categoryID          :Translator Hub category ID to use
                       for calls to the translator
                       service.

**Comment by holmbergius** [comment]
Thank you!!!!
