### ISSUE TITLE
Microsoft Translator full integration with MSWORD

### ISSUE THREAD

**Issue by DarrellJonsson** [MicrosoftTranslator/DocumentTranslator#46]
While this Microsoft Webpage (and the image below) demonstrates the full document (text and formating) of Microsoft Translator with MS WORD using [Translate] under the Review [menu.](https://www.microsoft.com/en-us/translator/word.aspx)...

...I'm unable to get MS WORD or OFFICE 365 or MS WORD online to have the same behaviour.

In all cases MS WORD and OFFICE 365 when using the Review/Translate button, triggers an IE Explorer window and returns the Docx stripped of all images and formatting.

* What MS WORD product actually can do what this image illustrates?
* Or do I need to program MS WORD to integrate with the MS Translator App to get this result?

In any case I'm mystified why MS would put this demo online if they don't have a ready made product that can do it, as all of the MS WORD variants I've tried do not do what is illustrated.

Format: ![Alt Text](https://c.s-microsoft.com/en-us/CMSImages/Word-Translator_whole-document.gif?version=9591a938-0997-b411-26a4-df5c3c72d4c5)

For more info see.
[https://c.s-microsoft.com/en-us/CMSImages/Word-Translator_whole-document.gif?version=9591a938-0997-b411-26a4-df5c3c72d4c5](url)

**Comment by DarrellJonsson** [comment]
For Office 2007 there was a wizard offered to do something that sounds like the above but does not work with later Office versions.
SEE : Adding Microsoft Translator as the default translator for the Research task pane.
[https://www.microsoft.com/en-us/download/confirmation.aspx?id=5780](url)
This though is not a current solution.

**Comment by chriswendt1** [comment]
Office 365 subscription does this.

**Comment by DarrellJonsson** [comment]
>> Office 365 subscription does this.

I loaded Office 365 subscription on a workstation and this feature was not on it.

Do you mean office 365 as installed on a workstation or are you referring to MS WORD
inside some kind of office 365 cloud service?
