### ISSUE TITLE
Error with PDFs files

### ISSUE THREAD

**Issue by juanSGS** [MicrosoftTranslator/DocumentTranslator#51]
Folowing error with any PDF
any ideas??
![error](https://user-images.githubusercontent.com/38533599/38999189-87680a5a-43f1-11e8-94c5-c4c5009ecce0.jpg)

**Comment by chriswendt1** [comment]
Document Translator uses Office to convert the document from PDF to DOCX. Something happened during that call into Office. Please open the PDF in Word, save as DOCX, and then run Document Translator on the DOCX. If that works, you are probably good and can run the conversion from Document Translator next time.
If it doesn't work, something wrong with the install of Office or a wrong version. Try 2016 or later.

Let me know if this helps.

**Comment by juanSGS** [comment]
Hi Thanks , tried the conversion in Word and works, but still the same error when running the PDF on translator. Office version is 2016 so we seem to be good , i have reinstalled MS Translator just in case but no luck.... 
best regards

**Comment by chriswendt1** [comment]
It takes a long time, but an uninstall and reinstall of Office 2016 may help.
When you manually read and saved PDF as DOCX in Word, were you running as the same user as when you ran document translator? I am thinking permissions problem.

**Comment by juanSGS** [comment]
Yes , did it with the same user and he has admin rights on the machine, checked access to the directories and all ok. 
Could an install of Visio 2016 impact it? this is the only thing that happened on that PC ; it was working nicely before...

**Comment by chriswendt1** [comment]
Version 2.1.0 includes a newer version, the NuGet versions of the Office interop libraries, and a new OpenXmlPowerTools drop. Can you try it with 2.1.0 or later?

**Comment by chriswendt1** [comment]
I did not see this problem again.
