### ISSUE TITLE
Is Microsoft Document Translator Using New Microsoft Translator API V3 compliant to GDPR?

### ISSUE THREAD

**Issue by HarshadPatel1988** [MicrosoftTranslator/DocumentTranslator#55]
Recently Microsoft has issued new Microsoft Translator API V3. Can you please let us know if the current version of Microsoft Document Translator is using the latest Microsoft Translator API V3, or still uses the old version?

**Comment by chriswendt1** [comment]
Still uses the old version. We'll update it in the next few weeks.

**Comment by HarshadPatel1988** [comment]
Thanks Chris.. :+1:
