### ISSUE TITLE
Document Headers & footers are not translated

### ISSUE THREAD

**Issue by joseairesfernandes** [MicrosoftTranslator/DocumentTranslator#56]
Hi,

We noticed that document headers and footers are not processed in Word documents. Please fix whenever possible.

Kind Regards,
Jose

**Comment by chriswendt1** [comment]
Thanks. I noticed that too. Will have a look.

**Comment by TGuiMel** [comment]
I made a pull request addressing the same issue. Hope that helps!

**Comment by chriswendt1** [comment]
Shipped in version 2.1.0. Updated binaries available.
