### ISSUE TITLE
Office 2016 support

### ISSUE THREAD

**Issue by jsypkens** [MicrosoftTranslator/DocumentTranslator#57]
A recent update added **OpenXmlPowerTools.MarkupSimplifier.SimplifyMarkup** - this addition has made some improvements to the process and to the translation, but the latest version of the nuget package has an issue, and doesn't support documents created or saved by Office 2016.

There is a pending pull request for OpenXmlPowerTools, but it's been pending for well over a year now. See this issue here:
https://github.com/OfficeDev/Open-Xml-PowerTools/issues/102

As a workaround, I cloned the project from the fixed branch, here:
https://github.com/ManoShu/Open-Xml-PowerTools/tree/office2016support

Then I removed the OpenXmlPowerTools nuget package, added this project to my solution, and added a reference in the business project to the openxml project. This resolved my issue.

To reproduce the issue, create or save any word document with Word 2016. Once the translation is finished, word will complain that the XML is invalid.

**Comment by chriswendt1** [comment]
Thanks a lot for the tip, @jsypkens. Integrated that branch of OpenXmlPowerTools into release 2.1.0. Binaries published as well. Should improve the translation quality noticeably.
