### ISSUE TITLE
Category is invalid

### ISSUE THREAD

**Issue by MrTantum** [MicrosoftTranslator/DocumentTranslator#59]
I finally managed to create valid model in the Custom Translator app.

Afterwards I tried to use this model in the Document Translator App but it is not possible to add this model in the app settings.

The error message says:

_Category is invalid 
Please visit https://hub.microsofttranslator.com to determine a valid category ID, leave empty, or use ane of the standard categories._ 

I copied the category ID from the Project Overview page.

![grafik](https://user-images.githubusercontent.com/31658807/40576324-71f4e678-60f4-11e8-9136-95ecf19ebb85.png)

Is this the correct Category ID? 
Or does it maybe take some time until the model is valid. The documentation in Microsoft Translator Custom Translator User Guide states:

> As soon as the system is deployed, you can use it via the Microsoft Translator Text API, or any 
> application that uses the API. Be sure to identify the correct Category ID in the API translation request.

**Comment by HarshadPatel1988** [comment]
I have the same question. Does the tool need to be updated to call new custom translator API instead of hub?

**Comment by chriswendt1** [comment]
I believ ethis is fixed in 2.0.4 and later. Please reopen if that is not the case. Before 2.0.4 the command line could not use the V3 API.
