### ISSUE TITLE
latest release not working on Windows 10

### ISSUE THREAD

**Issue by danvanderboom** [MicrosoftTranslator/DocumentTranslator#6]
I'm getting this error when trying to use the latest "stable release" of Microsoft Document Translator:

Error while processing document: <filename> Retrieving the COM class factory for component with CLSID {000209FF-0000-0000-C000-0000000000} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).

<img width="545" alt="screen shot 2016-05-08 at 6 41 48 am" src="https://cloud.githubusercontent.com/assets/2482850/15097862/31d099a2-14e8-11e6-81a0-54008c0d6e73.png">

I tried the newest prerelease, and got a different error there.

Because the code is available here and it looked like a Visual Studio file, I cloned this repo and tried opening it with Visual Studio 2015 Update 2, but got more error messages that I had the wrong version.

**Comment by chriswendt1** [comment]
Thanks, Dan, for reporting.
Can you say which OS locale you are working under?
I had gotten previous reports that the app doesn't work in certain locales, but I haven't gotten to the bottom of it.
I'll debug with your locale.

**Comment by danvanderboom** [comment]
English, EN-US if I recall the format accurately.

**Comment by chriswendt1** [comment]
Thanks. Under en-us locale the app is certainly working for me.
Does it work with other file formats besides PDF? Can you try plain text or .DOCX?
Reading PDF needs Office 2013 or later installed on your machine.

**Comment by chriswendt1** [comment]
Searching for the error indeed points to the installation of Office.
I recommend to open the PDF in Office, save as DOCX, and then use Document Translator on the DOCX. Document Translator does not need Office installed to translate DOCX file format.

**Comment by danvanderboom** [comment]
Thanks Chris. I was able to translate some PowerPoint documents without error. I attempted to open the PDF in Word, but I'm using the Mac version of Office and it doesn't seem to want to open that. Maybe it's a Windows-only Office feature, or do I need some kind of plugin?

Either way, a check for Office being installed (with compatible version) would be a good addition to the demo.

I'll find a way to get my PDF converted to Word and try again with that.

Thanks for your help, Chris.

**Comment by buchizo** [comment]
I want to this feature not depend on Office.

**Comment by chriswendt1** [comment]
Hi @buchizo,
Office is required only for translating .doc, .ppt, .xls (meaning pre-Office 2013 documents) and PDF. Office has the proprietary reader for these, Document Translator doesn't. The Office 2013 and later native document format is OpenXML, which Document Translator reads and writes directly. Document Translator also translates HTML and plain text without having Office installed.

Let me know if this answers the issue sufficiently.

**Comment by buchizo** [comment]
@chriswendt1 I agree that required Office for old office format document. PDF? I guess convert to docx from pdf using Office, right? I want to transfer pdf. Because in my case, I use DocumentTranslatorCmd.exe on server.

**Comment by chriswendt1** [comment]
In other context we use the PDF converter https://www.pdflib.com. It runs well on server.
