### ISSUE TITLE
Chinese to English PDF translation

### ISSUE THREAD

**Issue by lispeedyg** [MicrosoftTranslator/DocumentTranslator#62]
Hi,
I've successfully installed and run the application against the above PDF.  The process successfully writes out a docx file.  But, there is no translation.  It appears that the PDF to docx export simply pastes images of the original PDF into a document container.  And, no translations is performed on the images.

Can someone give me any clues as to where I've gone wrong?

Thanks.

**Comment by chriswendt1** [comment]
PDF can contact text or images. Document Translator only translates text. It does not perform OCR. I suspect your PDF contains images.
