### ISSUE TITLE
Release 2.0.2U is very slow, misses headers, and does not translate the entire document

### ISSUE THREAD

**Issue by TjamalPCL** [MicrosoftTranslator/DocumentTranslator#63]
Hello,

The newest version (2.02U) takes significantly longer to run than version 1.6.0U, also it does not seem to be translating headers.

**Comment by TjamalPCL** [comment]
Also it does not seem to always translate the entire document. I just had the document translator report "Translation completed successfully."; however, only the first part of the document was translated.

**Comment by chriswendt1** [comment]
I think 2.0.3 fixes that, at least it translates the complete document. Please reactivate of you still see an issue.
