### ISSUE TITLE
UI in french

### ISSUE THREAD

**Issue by 3moonjupyter** [MicrosoftTranslator/DocumentTranslator#64]
Hello,
It was mentioned in the release notes that the french UI was supposed to be available in the 1.5 version, however it is still not functional in the 2.0.2 version.

Thank you!

**Comment by chriswendt1** [comment]
The work just completed. Merged into master. Will be in all binaries following 2.0.5. Please feel free to submit issues or PRs against the French localization or functionality, if you see it.
