### ISSUE TITLE
Getting credentials are invalid on CLI but not on desktop client

### ISSUE THREAD

**Issue by zell12** [MicrosoftTranslator/DocumentTranslator#65]
I'm trying to use the translator via command line but I'm receiving 'Credentials are invalid' error when using the same apikey that I used on the desktop client that's working.

![image](https://user-images.githubusercontent.com/15136766/42804692-4c3dae0e-89dc-11e8-9261-6800943825c3.png)

![image](https://user-images.githubusercontent.com/15136766/42804791-8cf94cbe-89dc-11e8-988c-bd61178ecf14.png)

Note, I also tried using the apikey I've managed to get to work in the past, but now it's not working as well.
![image](https://user-images.githubusercontent.com/15136766/42804877-d6126c82-89dc-11e8-816a-e10f53b7d795.png)

**Comment by apoblock** [comment]
The issue happens because TranslationServices.Core is using different version of System.Net.Http - version 4.3.3 should be referenced with the Nuget package, rather than 4.1.1.2 from the framework.

**Comment by chriswendt1** [comment]
Thanks @apoblock for the suggestion. I tried that fix: didn't heal the problem. Interestingly works fine when run in VS, just not standalone.

**Comment by chriswendt1** [comment]
Fixed in 2.1.0 by copying system.net.http.dll.
