### ISSUE TITLE
Headers and Footers being ignored

### ISSUE THREAD

**Issue by iambrockmoir** [MicrosoftTranslator/DocumentTranslator#66]
In one of the earlier versions the headers were being translated.  Now it ignores the headers, it also ruins any page numbering that was present in the original word document.

**Comment by joseairesfernandes** [comment]
I agree. Translation of headers and footers is not working anymore. 
It will be good to recover this functionality since it's very useful.

**Comment by chriswendt1** [comment]
Headers and footers translated again in version 2.1.0. Let me know if you see otherwise.
