### ISSUE TITLE
Bad assumption about HTML content

### ISSUE THREAD

**Issue by rectorsquid** [MicrosoftTranslator/DocumentTranslator#7]
The code assumes that an HTML file will have a title. The code below gets an object then never tests to see if it is valid. A missing title causes the entire translation process to fail. This is a bad assumption and completely unnecessary:

            var title = htmlDoc.DocumentNode.SelectSingleNode("//head//title");
            title.InnerHtml = TranslationServices.Core.TranslationServiceFacade.TranslateString(title.InnerHtml, fromlanguage, tolanguage, "text/html");

**Comment by chriswendt1** [comment]
Thanks. Good find. Fixed and refreshed release.
