### ISSUE TITLE
Translated Documents Command Error

### ISSUE THREAD

**Issue by RoopeshMedixsoft** [MicrosoftTranslator/DocumentTranslator#77]
TranslationAssistant.AutomationToolkit\bin\Debug>DocumentTranslatorCmd.exe setcredentials /APIkey:apiKey translatedocuments /documents:c:\\testdocuments\\Name1.docx /from:en /to:el

When i am executing above command in command prompt getting below error:

Argument [APIkey] has value [apiKey].
Argument [categoryID] has value [].
ERROR: Unknown input argument [translatedocuments].
ERROR: Error in arguments.

APIKey is valid but translateddocuments is throwing argument error.

**Comment by chriswendt1** [comment]
Turn this into two separate commands. One line for setcredentials, one line for translatedocuments. Can't do it in a single line.
