### ISSUE TITLE
API support for document translate

### ISSUE THREAD

**Issue by nitinkcv** [MicrosoftTranslator/DocumentTranslator#8]
Are there any API's that's available for document translate? I could find the API's [here](https://msdn.microsoft.com/en-us/library/ff512419.aspx) which support translating texts but couldn't find any for document translate.

**Comment by chriswendt1** [comment]
Document Translator has a command line interface. Do you mean it should run as a web service and provide a web service API to translate documents? Good idea.

**Comment by mknwebsolutions** [comment]
@nitinkcv I've coded a fully web based translation engine via MSFT's API @ pairaphrase.com - contact me for any questions: mike@mkn.us

**Comment by chriswendt1** [comment]
Or run document translator on a server and receive the documents via API. Command line interface should allow you to do that.
