### ISSUE TITLE
Error tranlating PDF files

### ISSUE THREAD

**Issue by mahlzeit** [MicrosoftTranslator/DocumentTranslator#80]
When trying to translate PDFs, the following error message is displayed:

> Error while processing document [...]. Could not load file or assembly "Microsoft.Office.Interop.Word, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" or one of its dependencies. The system cannot find the file specified.

I can open the PDF in Word 2016, so the workaround of storing the PDF as DOCX works.

**Comment by chriswendt1** [comment]
Document Translator relies on the Office interop libraries and they in turn need to find Office on your machine in order to convert the PDF to DOCX. In this case Document Translator was not able to open Office. Sometimes a reinstall of Office helps.
