### ISSUE TITLE
errors with French chars 

### ISSUE THREAD

**Issue by juanSGS** [MicrosoftTranslator/DocumentTranslator#86]
when translating from french "Le présent dossier d'appel d'offres " funny enough I get 
"The PRUSAtender dossier is intended toUSAfinish the modalitiesUSAs "
So the accent is being translated to USA ????
Sorry no clue !!

**Comment by juanSGS** [comment]
Thanks it works , whats the cause of the error? any funny formatting??

**Comment by juanSGS** [comment]
> Can you try to reset the format of the sentence? Select the whole sentence, press Ctrl-Space.
> If this was a PDF, load in Word first, reset the format, save as .docx, then translate.

Wonder what kind of formatting could cause the issue since it happened all over the doc, I selected all and apply CTRL+SPACE and worked fine but I lost all the doc format. Any idea?
Thanks !

**Comment by chriswendt1** [comment]
If you have a formatting boundary or transition inside a word, bad things happen. Document Translator applies some gentle simplification of the segmentation using the OpenXML libraries, but not enough to overcome this problem, at least not consistently.

**Comment by juanSGS** [comment]
Clear !! thanks so much
