### ISSUE TITLE
Strange translations 

### ISSUE THREAD

**Issue by juanSGS** [MicrosoftTranslator/DocumentTranslator#87]
Dear team 
got quite a funny translation for an hungarian document when the tool translate it to English  : 

 "Budaörs, Budapest" (location) is translated to  "John, London" 
and  "ŐSZE Róbert" (person name in Hungarian) is translated for not good reason to "Krishnan R"
Strange indeed 
Thanks so much in advance for your help
Best regards

**Comment by chriswendt1** [comment]
This can happen. It is not an issue with Document Translator, it is an issue with the servoice itself, in the category of bad translatrions. You may try again now or in a month when we update the service backend.
