### ISSUE TITLE
Unable to cast COM object

### ISSUE THREAD

**Issue by AlexanderTodorovic** [MicrosoftTranslator/DocumentTranslator#88]
Dear All,
trying to translate japanese pdf document to english runs into
unable to cast COM object of type 'Microsoft.Office.Interop.Word.ApplicationClass'
to interface tyoe 'Microsoft.Office.Interop.Word._Application'.
...
Error loading type library/DLL.

Opening the document in Word and saving as .docx and translating then works fine as workaround.

Thx,
Alex

**Comment by chriswendt1** [comment]
No good idea here other than trying to uninstall and reinstall Office. For some reason Document Translator, or more specifically the Office Interop libraries, did not manage to start Office or communicate with it. Your workaround is fine.
