### ISSUE TITLE
Latest version of Document Translator freezes when adding Custom Translator domain

### ISSUE THREAD

**Issue by rebeccaballantyne** [MicrosoftTranslator/DocumentTranslator#96]
When adding a Custom Translator domain in the "Settings" page, the latest version of Document Translator always freezes and hangs. Only force closing the window & re-opening it remedies the problem.

**Comment by chriswendt1** [comment]
Fixed in 2.4.1 by making the validation async. 
Please test it with a cold deployment and let me know how it goes.

**Comment by rebeccaballantyne** [comment]
Validated, thanks.
